### ISSUE TITLE
Facebook এর ভিডু লিংক দিলে গায়েব করে দেয়

### ISSUE THREAD

**Issue by anupdebnath** [sarim/discord-embed-supercharger#1]
`https://www.facebook.com/watch/?v=467223540525548`

![image](https://user-images.githubusercontent.com/424585/160833433-175557b1-f54c-4e68-abf2-df3717ca0d31.png)

**Comment by sarim** [comment]
Fixed in f98be959ab8914ec0d4ec7a8882911f5336329a7
